### ISSUE TITLE
Possible problem with configure_file overwritting common/preprocessing.*

### ISSUE THREAD

**Issue by cappelletto** [MecatronicaUSB/uwimageproc#16]
In **master** branch, current CMakeLists.txt of **histretch** module includes:
``configure_file(scripts/preprocessing.cpp.in ../../common/preprocessing.cpp @ONLY)
  configure_file(scripts/preprocessing.h.in ../../common/preprocessing.h @ONLY)
``

this may overwrite existing preprocessing.* files. Is this an intended feature? I think it should be backward, the cmake config file retrieves the existing preprocessing in common, and copies (after configuration) in its own module source directory.

**Comment by vgarciac** [comment]
It was a temporal solution implemented by @fmoralesh to achieve a correct CPU-GPU build in histretch module. The current **preprocessing.cpp.in** file contains the final source code for preprocessing functions for all modules, included the *Cmake flags* to detect GPU usage.
This solution attend the necessity to use a GPU-histretch function, if CUDA support is detected in own module build, since the GPU-histretch function resides in common module.

**Comment by fmoralesh** [comment]
Used add_definitions(-DUSE_GPU) directive in Cmake files of **histretch** and **videostrip** module, making no longer necessary the scripts files (fix solution of #10 ). Both modules have been cleaned with CPU and GPU support.
